### ISSUE TITLE
USB-ID for e.g. Mouse wiggler ?

### ISSUE THREAD

**Issue by ranseyer** [wagiminator/CH552-MouseWiggler#1]
Hi Stefan,

do you think it possible to use a specific vendor/USB ID for the mouse wiggler or other sw-procjects with  this CH552 PCB ?

(Think about using the ID of existing devices, in your own house. For shure not for distributing this things...) 

Best
Ranseyer

**Comment by wagiminator** [comment]
Hi, the IDs can be changed in src/config.h of the respective firmware folder.

**Comment by ranseyer** [comment]
Thank you for the feeback. I closed the "issue". 
PS I send you an email if you want to "give" a pcb to me ...
